FROM golang:1.22-bullseye AS builder

WORKDIR /go/src/github.com/KineticCommerce/kinetic-cli

COPY go.mod go.mod
COPY go.sum go.sum

ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN go mod download

COPY . .

RUN go build -o /usr/bin/kinetic-cli .

FROM gcr.io/distroless/static-debian11:nonroot AS runner

COPY --from=builder --chown=nonroot:nonroot /usr/bin/kinetic-cli /usr/bin/kinetic-cli

ENTRYPOINT ["kinetic-cli"]
CMD ["kinetic-cli"]
